### ISSUE TITLE
IllegalStateException: Failed to lock offset 0 of .../daemon/registry.bin within 20.0 seconds

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#102]
Happens intermittently on all OSes, e.g. here https://github.com/mvndaemon/mvnd/runs/1266804259?check_suite_focus=true
I also have seen happening it locally when building with `-Dmrm=false`

**Comment by ppalaga** [comment]
I have never seen this when using `mvnd` for real builds. I saw it only when running our integration tests. I wonder how much is that a real issue and how much is it given by the way how we run our integration tests. 

Actually `Failed to lock offset 0 of .../daemon/registry.bin` sounds like the file exists but was truncated? If it is the latter we could e.g. consider having separate registry files for the individual itests.

**Comment by gnodet** [comment]
The current test setup uses a mvnd registry specific to each tests: `[mvnd]/integration-tests/target/mvnd-tests/SingleModuleTest/home/.m2/mvnd/registry/0.0.13-SNAPSHOT/registry.bin`

**Comment by ppalaga** [comment]
Another attempt to avoid this issue: https://github.com/mvndaemon/mvnd/pull/244/commits/b8ed8b19af420e782c4de2bdad0161c5fd26d0d0

**Comment by ppalaga** [comment]
Seems to be fixed by 73dec36
