### ISSUE TITLE
Provide a homebrew package

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#106]
like ist is done in [jbang](https://github.com/jbangdev/jbang/blob/master/.github/workflows/publish-packages.yml#L25-L30)

cc @chirino

**Comment by michael-simons** [comment]
I am a happy home-brew user and here's a shot at it:

https://github.com/michael-simons/homebrew-mvnd

Feel free to take it and incorporate it into mvnd. 

The test executes nicely and apart from being a binary dist, it should fulfill brews audit. 
Maven itself is setup similar, so that should be that big problem.

Anyway, thanks for a great project! Cheers.

**Comment by michael-simons** [comment]
(The tap is Mac only atm).

**Comment by ppalaga** [comment]
Much appreciated, thanks a lot, @michael-simons!

Would you like to transfer the ownership of your repo to the `mvndaemon` github org? I hope @gnodet is not against that.
I'd make you a committer in the new repo if you are interested.

**Comment by michael-simons** [comment]
Sure thing, but I can't. Guess I must be a committer first.

> You don’t have the permission to create public repositories on mvndaemon

**Comment by ppalaga** [comment]
> > You don’t have the permission to create public repositories on mvndaemon

Should be fixed now

**Comment by michael-simons** [comment]
Thanks, Peter! This is a highlight of my day! Ownership transferred, readme fixed. 

I have one 10.13.6 Mac here  that gives me socket time out… Something I'm gonna investigate today. 3 machines work just fine, on that particular one the daemon starts but the client can't connect.

Anyway: Thanks a lot for `mvnd`, I find this incredible useful.

**Comment by ppalaga** [comment]
Perfect, thanks!

We should now add some code into our GH actions pipeline to auto-update the tab on release.

**Comment by ppalaga** [comment]
This mvnd release task 

https://github.com/mvndaemon/mvnd/blob/master/.github/workflows/verify.yaml#L277-L285

should now be able to trigger the homebrew update 

https://github.com/mvndaemon/mvnd/blob/master/.github/workflows/verify.yaml#L277-L285

I tested the trigger manually but we'll only see during our next release whether it works really.

**Comment by ppalaga** [comment]
0.0.10 was not 100% successful. I had to add one more fix https://github.com/mvndaemon/homebrew-mvnd/commit/3a922e4c5b2e5c555ee2dbc5e668268f6caa3418
I hope 0.0.11 will run flawlessly incl. the homebrew tap.

**Comment by ppalaga** [comment]
Yeah, the homebrew tap update worked flawlessly during the 0.0.11 release.

**Comment by michael-simons** [comment]
Great! 

Also, my Neo4j-OGM issues disappeared with 0.0.11 (the ones with the large output).
