### ISSUE TITLE
Should support core extensions

### ISSUE THREAD

**Issue by marcphilipp** [mvndaemon/mvnd#114]
Core extensions don't seem to get applied when using `mvnd`. Is that a known issue/limitation? 

To reproduce simply clone https://github.com/gradle/maven-build-scan-quickstart, and run `mvnd validate` vs. `./mvnw validate`. The latter prints a build scan link at the end, while the former does not.

**Comment by ppalaga** [comment]
This is an issue known solely thanks to your report :) Thanks!

**Comment by famod** [comment]
Big 👍 from me as this would also enable the combination of `mvnd` and https://github.com/vackosar/gitflow-incremental-builder

**Comment by famod** [comment]
It seems extensions registered in `pom.xml` via `<extensions>` or as plugins with `<extension>true</extension>` are _not_ affected!

**Comment by ppalaga** [comment]
We should test with .mvnd/extensions.xml

**Comment by gnodet** [comment]
Fwiw, extensions have been removed from [DaemonMavenCli](https://github.com/mvndaemon/mvnd/blob/master/daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java) in the initial work to allow the container to be created and reused.

I'm going to check if we can bring that back somehow.

**Comment by gnodet** [comment]
@marcphilipp fwiw, the Gradle extensions uses a non standard input handler, so even with https://github.com/mvndaemon/mvnd/pull/181  and a fix https://github.com/mvndaemon/mvnd/issues/180, this would not solve the usage of the Gradle extension.  It would require a custom fix to provide an implementation of `com.gradle.maven.extension.internal.dep.org.codehaus.plexus.components.interactivity` that could delegate to the one that a fix for #180 would provide.

**Comment by marcphilipp** [comment]
@gnodet Thanks for looking into it! I'll take a closer look once #180 is resolved.
