### ISSUE TITLE
Option to default to a simple log when using a single thread

### ISSUE THREAD

**Issue by famod** [mvndaemon/mvnd#116]
It would come in handy to able to opt-out of the log buffering in case you want a more default maven output, e.g. to compare runs to `mvn` in case `mvnd` is showing unexpected behaviour.
When building Quarkus with its 700+ modules, console can also become unresponsive for a while when everything is flushed at once at the end of the build.

**Comment by gnodet** [comment]
Hitting the `<enter>` key or `Ctrl+M` should mitigate this behaviour as the output of each module will be displayed once it has been built.  It could changed to be the default behavior...  Can you give it a try ?

**Comment by famod** [comment]
> Hitting the `<enter>` key or `Ctrl+M` should mitigate this behaviour as the output of each module will be displayed once it has been built.

Confirmed, thanks!

> It could changed to be the default behavior...

Well, if I would see the condensed status as described in README (which I don't, maybe because of #36?), then I would actually prefer the less noisy mode to be the default.
Ideally there should be a command line argument to switch to the more noisy mode und the icing on the cake would be if ad default could be configured in a config file (which the command line argument would override if present).

Btw, is there something like `MVND_OPTS` (analogous to `MAVEN_OPTS`)?

**Comment by jglick** [comment]
I would really like to opt out of the custom display (which by the way is broken in Emacs’ `M-x shell`), and the implicit `-T`, so that the behavior is as similar to `mvn` as possible.

**Comment by ppalaga** [comment]
> I would really like to opt out of the custom display (which by the way is broken in Emacs’ `M-x shell`

Could you please file a separate issue?

> ), and the implicit `-T`, so that the behavior is as similar to `mvn` as possible.

Could you please file a separate issue in which you explain why?

**Comment by jglick** [comment]
Another reason to want output to be displayed normally as it arrives: watching the progress of tests. I actually rolled back a Surefire update just because it broke this: https://github.com/jenkinsci/plugin-pom/pull/343

**Comment by gnodet** [comment]
@jglick the progress can also be seen in more details if you hit the '+' key 3/4 times during the build... (hit '-' to get revert).
It will display the last few lines for each module

**Comment by ppalaga** [comment]
I wonder, if we could automatically stretch the rolling log to the full screen in case there is just a single thread running?

**Comment by gnodet** [comment]
@ppalaga I was thinking about:
  * having an option to just display the events when they come (prefixed by the projectId to make it more understandable), this would be when running on a dumb terminal #131 
  * having an option to default to a simple log when using a single thread (i.e. just print the events when they come as maven does)
  * make the default rolling window size configurable (it currently defaults to 0, but it could be raised a bit by default, not sure)
