### ISSUE TITLE
Please give a meaningful name to the mvnd process

### ISSUE THREAD

**Issue by fbricon** [mvndaemon/mvnd#118]
While running `jps` on my machine, it didn't immediately occur\\ to me that ServerMain was the actual mvnd process.

```
❯ jps
79547 ServerMain
```

I had to jstack it in order to find a meaningful classname in one of the stacktraces.

So just please make it so that the mvnd process can be immediately identifiable when browsing running processes.

**Comment by fbricon** [comment]
yes you can do `jps -v` to get more useful infos, without needing to dig into jstack

**Comment by ppalaga** [comment]
OK, how about `fbricon's favorite build tool` ;)

**Comment by fbricon** [comment]
Works for me
