### ISSUE TITLE
Implement build cancellation

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#127]
Some support is already provided (such as a specific state and such) but we need to intercept the Ctrl+C / interrupt event, send a cancellation request and check on the daemon side.

**Comment by famod** [comment]
This would be a useful enhancement!
I ran `mvnd --debug` today and aborted it right away with ctrl+c but it took maybe 10-20 secs until cpu load of the daemon dropped from > 90% back to zero.

**Comment by herder** [comment]
Another enhancement would be that all the build output generated before Ctrl-C was output to the console on interrupt. Currently, it is lost unless we wait until the build is finished.
