### ISSUE TITLE
Split daemon module into daemon and dist

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#130]
The daemon module currently contains two things:

1. Java code that depends on mvnd-common which is packaged as mvnd-daemon.jar

2. The distro that also depends on mvnd-client

As a result, the whole module has to depend on mvnd-client, which is not good because we can inadvertently start depending on Java code from mvnd-client. That would break our Java 8 compatibility.

To solve the above problem, I propose to split the current daemon module into daemon and dist. daemon would depend only on mvnd-common and dist would depend on both mvnd-daemon and mvnd-client.

**Comment by gnodet** [comment]
Sounds good to me.
