### ISSUE TITLE
Opt out of implicit -T

### ISSUE THREAD

**Issue by jglick** [mvndaemon/mvnd#132]
I am not sure how I feel about the implicit `-T` argument being added by default, but there should at least be a user setting to disable it by default (without adding `-T1` to every invocation):

* Principle of least surprise. It should be possible to use `mvnd` as a drop-in replacement for `mvn` with as few risks as possible. Parallelized builds are not enabled by default in Maven, so if there are problems in mojos or POMs which are manifested only in this mode, it would effectively look like a bug in `mvnd`.
* The dynamic console output was apparently invented with `-T` as the motivating use case, and there are reasons to not want it, as in #116.

**Comment by ppalaga** [comment]
https://github.com/mvndaemon/mvnd/pull/176 will allow storing your `-T` preference in `~/.m2/mvnd.properties`:

```
mvnd.threads = 1
```

**Comment by famod** [comment]
Good to have a config option for this!

What if a certain project cannot be built multi-threaded? I guess in this case one has to resort to passing `-T1` for each run?

**Comment by ppalaga** [comment]
> What if a certain project cannot be built multi-threaded? I guess in this case one has to resort to passing `-T1` for each run?

Yes, currently, there is no better option.

If you mean that we should have a per-project config file, feel free to create a new issue.
