### ISSUE TITLE
Provide build output when cancelling a job

### ISSUE THREAD

**Issue by herder** [mvndaemon/mvnd#142]
When pressing Ctrl-C to cancel a job, the Maven output so far is not given.

It would be great to get the output that has been produced by Maven, and possibly an opt-out setting if we want the current behavior.

**Comment by ppalaga** [comment]
This sounds related to https://github.com/mvndaemon/mvnd/issues/127 Would you mind commenting there and close this one?

**Comment by herder** [comment]
Done, thanks!
