### ISSUE TITLE
Set maven version like maven-wrapper

### ISSUE THREAD

**Issue by herder** [mvndaemon/mvnd#143]
To ensure repeatable builds in a CI environment it would be great to be able specify desired maven version, like the [Maven Wrapper plugin](https://github.com/takari/maven-wrapper). 

Or possibly detect if `mvnw` is present in the project directory and use that?

**Comment by ppalaga** [comment]
It is true that we embed Maven, but we modify it slightly. Pulling a random Maven version during the build and running with it would be rather risky because we test only against a single particular Maven version.

Having our own `mvndw` script would perhaps solve your problem too? I think that kind of solution would be more robust and I'd be open to accept such a contribution.

**Comment by ppalaga** [comment]
Oh, sorry I did not want to close.

**Comment by herder** [comment]
> Providing our own `mvndw` script that would pull a specific version of `mvnd` would perhaps solve your problem too? I think that kind of solution would be more robust and I'd be open to accept such a contribution.

That sounds like a good idea, if it's not possible to use Maven out of the box. 

Adding a `mvnd.version` property that can be passed to the command line or put in `mvnd.properties` would be the easiest way to use this, I guess?

**Comment by ppalaga** [comment]
I thought it could work the very same way as with stock Maven:

* A tool similar to Maven's wrapper plugin (`mvn -N io.takari:maven:0.7.7:wrapper`) would generate `mvndw` and `mvndw.cmd` scripts
* Those scripts would either call `mvnd` already installed somewhere under `~/.m2` (e.g. `/home/ppalaga/.m2/mvnd`) or they would download and install `mvnd` before calling it from there.

**Comment by soerenhenkel** [comment]
Hm. Not sure if I understand that correctly, but this kind of solution would "only" allow to select a specific version of mvnd (like e.g. 0.0.9), wouldn't it? 
I think in the end we would need to be able to select a specific mvn version (like e.g. 3.5.4, instead of 3.6.3 coming with mvnd).

**Comment by ppalaga** [comment]
> we would need to be able to select a specific mvn version (like e.g. 3.5.4, instead of 3.6.3 coming with mvnd).

I am quite sure that supporting older Maven versions is not a priority for me and @gnodet but we are still open to contributions in case anybody else would like to work on that.

**Comment by herder** [comment]
Would it be possible to summarize what modifications you need to do to Maven, @ppalaga ?
I could look it up I guess, but I might miss something :)

**Comment by ppalaga** [comment]
> what modifications you need to do to Maven?

Start with downgrading Maven around here: https://github.com/mvndaemon/mvnd/blob/master/pom.xml#L46
and then make all integration tests pass.

**Comment by helpermethod** [comment]
@herder Maybe not exactly the answer you are looking for, but:

With SDKMAN! it's possible to fix the `mvnd` version by using a `.sdkmanrc` file. That would allow you to use the same `mvnd` version with the same packaged `mvn` version on both dev machine and CI system (SDKMAN! can even configure the versions automatically on project directory entry).

The only thing missing currently is the functionality to automatically install the versions present in the `.sdkmanrc` file but I'm already working on it.

**Comment by herder** [comment]
Thinking about it this would maybe be better placed in the Maven-wrapper project? Since it downloads maven versions anyway, it might be easier to modify that script to either download the regular maven binary or a `mvnd`?

**Comment by gnodet** [comment]
Fwiw, I think it would be nice if we could get `mvnd` to easily layout on top of any (or at least a set of supported) maven versions.
The main problem is currently the way the `mvnd` daemon starts maven.  The `DaemonMavenCli` class has a bunch of changes compared to the default `MavenCli` so that we can reuse the same class loaders, else there can be no git happening and thus few benefits in using a daemon.  It needs to be investigate whether this can be done in a cleaner and less intrusive way.

**Comment by cyraid** [comment]
Would be nice to allow a way for, say, IntelliJ (which wants just a path to maven directory), to be able to enjoy the benefits just by running a 'mvn', and it will use the mvnd.

**Comment by gnodet** [comment]
I'm not planning to actually come up with something that would work with multiple maven versions as  `mvnd` is tightly coupled to maven unfortunately.

**Comment by gnodet** [comment]
> Question: what's the plan on support for the Maven 3.x stream?
> Will the Deamon be kept updated on that stream, or are we going to be forced to adopt Maven 4.x? (which might not be feasible for a lot of projects for some time).

I would think it will follow the maven 4.x stream. So we can plan on having mvnd with an embedded 3.x maven for some time.  The 0.9.0 release is under vote, and I'll soon start a 0.10.0 based on maven 3.9.0 which is also being voted.

**Comment by PukPukov** [comment]
>Providing our own mvndw script that would pull a specific version of mvnd would perhaps solve your problem too? I think that kind of solution would be more robust and I'd be open to accept such a contribution.

What about official download script/wrapper for mvnd itself? Considering there will be maven 4 release any moment that will unavoidably bring pain out of breaking changes, wrapping becomes mandatory.
