### ISSUE TITLE
Add a spinner, progress or something indicating that the build is going on

### ISSUE THREAD

**Issue by galegofer** [mvndaemon/mvnd#150]
Something a kind of cosmetic, but it may be useful to see a spinner, progress bar, or something indicating that the build is going on.
Right now is not very intuitive, and you get feedback just after the build finished.
Another alternative is just to show the plugins that are getting executed like:

- maven-jar-plugin:2.4:jar
- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ f2e-contract-test
-> maven-install-plugin:2.4:install - executing

**Comment by ppalaga** [comment]
I guess you are on Windows where we have some known display problems https://github.com/mvndaemon/mvnd/issues/36
Normally, the output should look like the following: https://asciinema.org/a/BwsKoBYfW9jsXlDG3QcxSSBEw?autoplay=1

**Comment by gnodet** [comment]
Fwiw, the windows problems should be fixed in a few hours...

**Comment by gnodet** [comment]
The display now has the progress information, si I'm closing that one.  Please reopen if needed.

**Comment by galegofer** [comment]
It works great at .0.0.11, good job!
