### ISSUE TITLE
Domain transfer offer

### ISSUE THREAD

**Issue by uweschaefer** [mvndaemon/mvnd#153]
Hi

first let me congratulate you to this project. I am excited by what it can do even at such an early stage. I happen to have started a thing with the same name and similar intent (minimize startup timer) two years ago. https://github.com/Mercateo/mvnd 
That impl at the time was based on a go client that connected to a maven daemon. It never left a prototype stage.

However what i have done back in the day i to register the domain 'mvndaemon.org', which i'd gladly offer to transfer for free to your project, if you can use it.

If this is of any interest, please let me know. If not - no hard feelings and keep up the amazing work.

**Comment by ppalaga** [comment]
Thanks for the kind offer, @uweschaefer! Let's discuss the details via e-mail.

**Comment by ppalaga** [comment]
Thanks a lot, @uweschaefer !

We have now migrated our groupIds and Java package names to `org.mvndaemon`. 

http://mvndaemon.org/ is redirected to https://github.com/mvndaemon/mvnd for now.

**Comment by Elmago34** [comment]
> Gracias por la amable oferta,@uweschaefer¡Discutamos los detalles por correo electrónico!

client/pom.xml
