### ISSUE TITLE
mvnd native executable is not passing -Dkey=val to the daemon

### ISSUE THREAD

**Issue by thiagolocatelli** [mvndaemon/mvnd#157]
I do have the following configuration for my `docker-maven-plugin` in the parent `pom.xml` for my multi module project:

```
	<plugin>
		<groupId>com.spotify</groupId>
		<artifactId>dockerfile-maven-plugin</artifactId>
		<version>1.4.13</version>
		<executions>
			<execution>
				<id>default</id>
				<goals>
					<goal>build</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<repository>${docker.user}/${project.artifactId}</repository>
			<tag>${project.version}</tag>
			<buildArgs>
				<JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
			</buildArgs>
		</configuration>
	</plugin>
```

each of my modules import this configuration using the following directive:

```
	<profiles>
		<profile>
			<id>docker</id>
			<activation>
				<property>
					<name>docker</name>
					<value>build</value>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>com.spotify</groupId>
						<artifactId>dockerfile-maven-plugin</artifactId>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>	
```

With the command `mvn clean package -DskipTests -P docker -Ddocker.user=thiagolocatelli` project builds successfully and my docker images are created, however when I use the command `mvnd clean package -DskipTests -P docker -Ddocker.user=thiagolocatelli` the project fail with the following error messages:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for homeflix-parent 1.0.0-SNAPSHOT:
[INFO]
[INFO] homeflix-parent .................................... SUCCESS [  0.182 s]
[INFO] user-service ....................................... FAILURE [ 10.839 s]
[INFO] rental-service ..................................... FAILURE [ 10.839 s]
[INFO] cart-service ....................................... FAILURE [ 10.840 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.523 s (Wall Clock)
[INFO] Finished at: 2020-10-26T10:20:39-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project user-service: Repo name "${docker.user}/user-service" must contain only lowercase, numbers, '-', '_' or '.'. -> [Help 1]
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project rental-service: Repo name "${docker.user}/rental-service" must contain only lowercase, numbers, '-', '_' or '.'. -> [Help 1]
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cart-service: Repo name "${docker.user}/cart-service" must contain only lowercase, numbers, '-', '_' or '.'. -> [Help 1]
```

Not sure this is a bug related to `mvnd` but it is only happening with `mvnd` on my local environment. The same error happen with other projects as well.

**Comment by ppalaga** [comment]
Thanks for the report, @thiagolocatell. I guess we need to set the properties in the Daemon JVM programmatically when starting a build.

**Comment by ppalaga** [comment]
Debugging a bit, it turns out that `-Dkey=val` style args are not passed to the `main(String[] argv)` method, while `-Dkey` are. This also explains why `-DskipTests` works and `-Ddocker.user=thiagolocatelli` does not.

**Comment by gnodet** [comment]
> Debugging a bit, it turns out that `-Dkey=val` style args are not passed to the `main(String[] argv)` method, while `-Dkey` are. This also explains why `-DskipTests` works and `-Ddocker.user=thiagolocatelli` does not.

Ah, I was suspecting something that. I think I've been hit by that already but had no time to investigate yet.

**Comment by thiagolocatelli** [comment]
But aren't "-D" arguments used as JVM arguments instead of application
arguments (String[] argh)? No "-D" should be available in the argh array,
correct?

**Comment by thiagolocatelli** [comment]
just wrote this simple example, `-Dkey=val` and `-Dkey` are indeed available in the argv array in the main method if they are used as application arguments, but not if they are used as JVM arguments.

```
class Main {
  public static void main(String[] args) {
    System.out.println("Command-Line arguments are");

    // loop through all arguments
    for(String str: args) {
      System.out.println(str);
    }
  }
}
```

execution:

```
[thiago@dropzone ~] java -DskipTests -Ddocker.user=thiagolocatelli Main clean package
Command-Line arguments are
clean
package

[thiago@dropzone ~] java Main clean package -DskipTests  -Ddocker.user=thiagolocatelli
Command-Line arguments are
clean
package
-DskipTests
-Ddocker.user=thiagolocatelli
```

**Comment by ppalaga** [comment]
Yeah, @thiagolocatelli this is how stock `java` works. `mvnd` is a native executable built with GraalVM and apparently, its behavior is slightly different here. Note that with `mvnd` the ordering of the args plays no role.

**Comment by thiagolocatelli** [comment]
@ppalaga understood. Should the parameters somehow be parsed in the client native binary to identify which ones are system properties format (`-Dkey=val`) and then convert them to system properties when sending the execution to the daemon? Would this be a valid approach?

**Comment by ppalaga** [comment]
It is not easy. We have to figure out.

**Comment by ppalaga** [comment]
`-H:-ParseRuntimeOptions` looks very promissing https://github.com/oracle/graal/issues/779#issuecomment-436274256

**Comment by thiagolocatelli** [comment]
I hope that works since I see you are already parsing the parameters on https://github.com/mvndaemon/mvnd/blob/6e461885863e745881ab2ceeabc50c83aa46f30f/client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java#L111.

**Comment by thiagolocatelli** [comment]
Thank you for the fix @ppalaga , once the new build is available on sdkman I will pull it and test it here.

**Comment by ppalaga** [comment]
You can also test with the zip attached to the build of the PR https://github.com/mvndaemon/mvnd/pull/159/checks - it is under Artifacts in the top right corner

**Comment by ppalaga** [comment]
Thanks for the report, this is a very good catch!

**Comment by thiagolocatelli** [comment]
@ppalaga It says "mvnd cannot be opened because the developer cannot be verified". Anything extra I have to do to run the binary?

**Comment by thiagolocatelli** [comment]
ok, I ran using the shell script

```
Building gracenote-parent  threads: 7  time: 20s  progress: 5/8 62%
:gracenote-csv-exporter-605:com.spotify:dockerfile-maven-plugin:1.4.13:build {execution: default}
:gracenote-history-loader-605:com.spotify:dockerfile-maven-plugin:1.4.13:build {execution: default}
:gracenote-data-loader-605:com.spotify:dockerfile-maven-plugin:1.4.13:build {execution: default}
```

it worked. Thank you so much

**Comment by thiagolocatelli** [comment]
@ppalaga any idea of how I can run the binary without getting that popup from MacOS?

**Comment by isaacaggrey** [comment]
This is the closest issue describing what I was running into but mvnd by default consumes the `-D` args it seems. For instance, if you want to run a single test (via `-Dtest=MyTestClass`), you need to use the long form (instead of -D): 

```bash
mvnd test --define test=MyTestClass
```

This is still an issue on mvnd 1.0.5.

**Comment by ppalaga** [comment]
@isaacaggrey thanks for the report, however this issue is closed. Could you please file a new one?
