### ISSUE TITLE
How to pass jvm args to mvnd ?

### ISSUE THREAD

**Issue by happysomani** [mvndaemon/mvnd#174]
I am trying to use mvnd in my project and I hit this issue where the build fails with "Too many open files error".  I want to be able to pass the flag -XX:+MaxFDLimit flag to mvnd.  Would you happen to know how I can achieve that?

**Comment by ppalaga** [comment]
Yeah, this is a valid issue. There was some discussion about this in https://github.com/mvndaemon/mvnd/issues/122#issuecomment-715887523

**Comment by gnodet** [comment]
We need to define an additional property that will be used to pass additional arguments when the daemon is created.
This property would have a default of `-Xmx4g` as we have now, and it would have to be a discriminating factor between daemons (i.e. select a daemon which has the same matching property).
In all cases, we need to be able to make those startup properties configurable, so...
