### ISSUE TITLE
maven-checkstyle-plugin: NoSuchMethodError: 'void org.slf4j.spi.LocationAwareLogger.log(org.slf4j.Marker, java.lang.String, int, java.lang.String, java.lang.Throwable)'

### ISSUE THREAD

**Issue by mikaelstaldal** [mvndaemon/mvnd#183]
in pom.xml:
```
      <plugin>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>2.17</version>
        <dependencies>
          <dependency>
            <groupId>com.spotify.checkstyle</groupId>
            <artifactId>spotify-checkstyle-config</artifactId>
            <version>1.0.7</version>
          </dependency>
          <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle</artifactId>
            <version>8.4</version>
          </dependency>
        </dependencies>
        <configuration>
          <configLocation>spotify_checks.xml</configLocation>
          <consoleOutput>true</consoleOutput>
          <!-- Remove or switch to false to keep building even with checkstyle errors -->
          <failOnViolation>true</failOnViolation>
          <logViolationsToConsole>true</logViolationsToConsole>
          <sourceDirectories>
            <sourceDirectory>${project.build.sourceDirectory}</sourceDirectory>
          </sourceDirectories>
        </configuration>
        <executions>
          <execution>
            <id>default</id>
            <phase>process-test-classes</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

Regular Maven build works fine, but with mvnd I get this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) on project contentdeploy-master-2: Execution default of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check: java.lang.NoSuchMethodError: 'void org.slf4j.spi.LocationAwareLogger.log(org.slf4j.Marker, java.lang.String, int, java.lang.String, java.lang.Throwable)'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-checkstyle-plugin:2.17
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
```

Environment:
```
$ mvnd --version
Maven Daemon 0.0.11-linux-amd64 (native)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/mikaelstaldal/bin/mvnd-0.0.11-linux-amd64/mvn
Java version: 11.0.9, vendor: Amazon.com Inc., runtime: /usr/lib/jvm/java-11-amazon-corretto
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-52-generic", arch: "amd64", family: "unix"
```

**Comment by ppalaga** [comment]
Thanks for the report, could you please try with the snapshot build attached to this recent CI run? https://github.com/mvndaemon/mvnd/actions/runs/344386815 
The fix there is a wild guess what could be the problem. I'll have revisit this if it does not help.

**Comment by herder** [comment]
First culprit to check is always the logging libraries :smile:

**Comment by mikaelstaldal** [comment]
I still get
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) on project content-deploy-master-2: Execution default of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check: java.lang.NoS
uchMethodError: 'void org.slf4j.spi.LocationAwareLogger.log(org.slf4j.Marker, java.lang.String, int, java.lang.String, java.lang.Throwable)'
```

**Comment by ppalaga** [comment]
I was able to reproduce and I was not able to find what the stock Maven does differently than we do. The ClassRealm of the checkstyle plugin contains basically the same jars: plexus-interactivity-api-1.0-alpha-4.jar is the only difference that they have and we don't have in the plugin ClassRealm. But that one should not matter.

Apparently, in the daemon, jcl-over-slf4j-1.5.6.jar's org.apache.commons.logging.impl.SLF4JLocationAwareLog sees org.slf4j.spi.LocationAwareLogger from jcl-over-slf4j-1.7.29.jar (that is available in the plexus.core realm - but that's the same with us and them) that does not contain log() with the required signature. The older LocationAwareLogger.log() variant is available in slf4j-jdk14-1.5.6.jar but for some reason it is not hit in the daemon in spite of being there in the plugin's class realm.

At least I have found a workaround: adding an explicit jcl-over-slf4j-1.7.29.jar to the plugin's deps solves the problem

```
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>jcl-over-slf4j</artifactId>
                        <version>1.7.29</version>
                    </dependency>
```

**Comment by mikaelstaldal** [comment]
Your workaround works for me.

**Comment by rmannibucau** [comment]
Is it possible to patch checkstyle plugin classloader from mvnd? A lot of projects are using 2.17 and it is a lot more work to patch them all than fixing it in mvnd.

**Comment by ppalaga** [comment]
> Is it possible to patch checkstyle plugin classloader from mvnd?

I'd prefer avoiding it as much as possible. Does the issue occur with newer checkstyle versions?

**Comment by rmannibucau** [comment]
@ppalaga I don't think so since in some other projects using the plugin it seems to work but main issue is that it is not about upgrading the plugin version but more rewriting the conf since checkstyle broke it all in between. What about a plugin which could be installed with sdk install mvd-plugin-checkstyle or so (in ~/.mvnd/plugins) which would do this job?

**Comment by gnodet** [comment]
The problem comes from the way `mvnd` is launched.  The jars that consist the main mvnd class path are leaking to plugins because the setup is slightly different.  I'll try to fix it so that we can have a classloader setup similar to the maven one.

**Comment by gnodet** [comment]
@rmannibucau Do you have a project that I can use to reproduce ? I thought I had the problem with maven master, but I can't reproduce it anymore...
