### ISSUE TITLE
The daemon created by the client should survive if the client is interrupted using Ctrl+C

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#193]
The JVM has a bad habit (for our use case) to still _own_ child processes.
This means that when the JVM receives an interrupt signal, it will forward it to child processes. 
The means that if the client creates a daemon receives a SIGINT, the daemon won't be able to survive.
The daemon needs to call `setsid` in order to detach.  The jansi library would be a good candidate for this function since it already contains a bunch of posix functions.

**Comment by ppalaga** [comment]
Is this the case only when the daemon is started from `mvnd.sh` - i.e. from a stock JVM? I am asking because the daemon seems to survive when I interrupt the `mvnd` native client with `CTRL+C`.

**Comment by ppalaga** [comment]
> the daemon seems to survive when I interrupt the `mvnd` native client with `CTRL+C`.

Plz. forget what I said. The daemon is killed indeed.

**Comment by gnodet** [comment]
Actually, a more simple way may be to simply have the daemon ignore the `INT` and `TSTP` signals, it would avoid any additional JNI requirement.
