### ISSUE TITLE
Clean the names of properties

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#221]
The environment properties are not always named in a consistent way.
We should make them more coherent.
One solution would be to have all properties beginning with `mvnd.` instead of `daemon.`
Also we have a few properties that use `.` to separate words instead of using a capital such as `mvnd.daemon.storage` or `daemon.core.extensions`.

**Comment by ppalaga** [comment]
+1 for `mvnd.`

`daemon.` does not sound specific enough. There are many daemons there in the world. `mvndaemon.` would work though.
