### ISSUE TITLE
When the build does not produce any output, the elapsed time can be sluggish

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#224]

**Comment by ppalaga** [comment]
Well, as long as the client is connected with the daemon, the KEEP_ALIVE messages keep the elapsed time to be updated. Yes, it is slugish while starting a new daemon. Or you have some other situation in mind?

**Comment by gnodet** [comment]
It's just the clock which is not really regular, so I'd like to lower the keep-alive time to 100ms so that the clock is updated regularly and not every 1.5s for example.  This should not cause too much additional traffic given the size of the message and given the client is simply waiting for any message to come in.

**Comment by ppalaga** [comment]
Ah, I see what you mean now. I have not observed that, perhaps because I am on a powerful machine with enough reserves to schedule the terminal updates on time. Yeah, KEEP_ALIVEs every 100ms is worth trying.
