### ISSUE TITLE
mvnd --help produces no output

### ISSUE THREAD

**Issue by fbricon** [mvndaemon/mvnd#238]
`mvnd --help` and `mvnd -h` don't work like with regular mvn. It's the kind of thing that'd be helpful to figure out if there's a solution for https://twitter.com/fbricon/status/1332252222932066305 for instance

**Comment by ppalaga** [comment]
Thanks, that's a good idea to document mvnd specific options via `-h/--help`.

You can get the regular rolling output via `mvn -Dmvnd.noBuffering=true`

**Comment by gnodet** [comment]
> Thanks, that's a good idea to document mvnd specific options via `-h/--help`.

Agreed.  @fbricon or are you suggesting we remove the line prefixes in this output (`[INFO] [stdout] `) ?

> You can get the regular rolling output via `mvn -Dmvnd.noBuffering=true`

It does not work for some reason that need to be investigated.  However using batch mode `mvnd --batch-mode` will force the non buffered output too.

**Comment by ppalaga** [comment]
I am fixing it https://github.com/mvndaemon/mvnd/issues/239
