### ISSUE TITLE
Let -h/--help display also mvnd specific options

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#243]

**Comment by gnodet** [comment]
The default line length of 80 is really ugly. The client uses JLine, so we do have the terminal width and we should send it to the daemon to properly format the help.  We could add a `getTerminalWidth` method to the `ClientOutput` for that and it could be sent as a system property to the daemon (an internal property such as `mvnd.terminalWidth`).  I'll work on that bit if you want.

Also, we should add a way to document the command line options such as `--start`, `--stop` and `--status` somehow as they seem to be missing from the help.

**Comment by ppalaga** [comment]
> @ppalaga The default line length of 80 is really ugly. 

I agree, and it is even less: 74. I just took the format used by the the stock `mvn --help`. 

>The client uses JLine, so we do have the terminal width and we should send it to the daemon to properly format the help. We could add a `getTerminalWidth` method to the `ClientOutput` for that and it could be sent as a system property to the daemon (an internal property such as `mvnd.terminalWidth`). I'll work on that bit if you want.

+1, that would be awesome.
 
> Also, we should add a way to document the command line options such as `--start`, `--stop` and `--status` somehow as they seem to be missing from the help.

Yes, that's not so hard. I plan to work on that.

**Comment by ppalaga** [comment]
Is this good to merge then?

**Comment by gnodet** [comment]
@ppalaga I'm working on the terminal width, but if you want to merge before, that's fine with me.
