### ISSUE TITLE
Add a simple command option to toggle maven-like behavior

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#248]
Something named either `--maven-like` / `-m` or `--single-threaded` / `-st` ?
The idea is to be a shortcut for `--builder singlethreaded -T1 -Dmvnd.noBuffering=true` options, so that the execution order and output is the same as a standard maven.

Toughts on the option name are welcomed !

**Comment by ppalaga** [comment]
Good idea, how about `--serial`/`-S` or even `-1` ?

**Comment by gnodet** [comment]
I'll go for `--serial`/`-S` which should allow an easy `mvnds` alias if needed.
