### ISSUE TITLE
Cannot build Quarkus after removing ~/.m2/repository/io/quarkus/ or ~/.m2/repository/io/quarkus/gizmo

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#26]
Steps to reproduce
```
rm -Rf ~/.m2/repository/io/quarkus/gizmo
git clone https://github.com/quarkusio/quarkus.git
cd quarkus
mvnd clean install -DskipTests -DskipITs -Denforcer.skip -Dquarkus.build.skip -DskipDocs
```

Expected: build success
Actual: ArC Processor and Qute Generator are complaining about missing gizmo during compilation:

```
[[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-2:compile[m [1m(default-compile)[m on project [36mqute-generator[m: [1;31mCompilation failure[m: Compilation failure: 
[[1;31mERROR[m] /home/ppalaga/orgs/quarkus/quarkus/independent-projects/qute/generator/src/main/java/io/quarkus/qute/generator/ValueResolverGenerator.java:[5,24] package io.quarkus.gizmo does not exist
...
```

```
[[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-2:compile[m [1m(default-compile)[m on project [36marc-processor[m: [1;31mCompilation failure[m: Compilation failure: 
[[1;31mERROR[m] /home/ppalaga/orgs/quarkus/quarkus/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationLiteralProcessor.java:[4,24] package io.quarkus.gizmo does not exist
```

It is very strange that there is no trace of gizmo in the local maven repo under `~/.m2/repository/io/quarkus/gizmo` I'd expect maven to download it. I do not see any download related error in the log.

**Comment by gnodet** [comment]
Yes, this is certainly a caching problem.  I suppose this one is caused by the https://github.com/gnodet/mvnd/blob/master/daemon/src/main/java/org/jboss/fuse/mvnd/plugin/CliPluginRealmCache.java which purpose is to cache the classloaders / classes for each plugin.   I think the current check verifies the input used to build the classloader, but not the files stored in the repository.  I assumed the existing files in the repository to be immutable. 
Actually, it could be related to #25 if using snapshots.

**Comment by ppalaga** [comment]
Oh, I see a simple workaround could be to stop the daemon after messing with local the repo.

**Comment by gnodet** [comment]
Yes, this can easily be done with `mvnd --stop`.

**Comment by ppalaga** [comment]
I can say after some debugging that this is not (at least directly) related to CliPluginRealmCache. The error is thrown by the compiler plugin whose class realm does not contain gizmo at all. It is the compiled classes depending on Gizmo. 

So it might by a class loader caching issue, but rather related to caching of project dependencies, or jars (maybe some variant of https://bugs.openjdk.java.net/browse/JDK-8246714 ) or similar. We should have a look how the compiler plugin assembles the build path and whether there is some Maven specific caching in place there.

**Comment by ppalaga** [comment]
Duplicate of https://github.com/mvndaemon/mvnd/issues/312
