### ISSUE TITLE
No reuse of daemons, no build speedup.

### ISSUE THREAD

**Issue by PokingUrsa** [mvndaemon/mvnd#261]
'Starting new daemon, 1 incompatible, 3 stopped'

Each time I invoke mvnd, it starts a new daemon, and there is no build speedup.  How does it check for a compatible daemon?

OS: Ubuntu 20.04
AMD Ryzen Processor
Oracle 1.8.0 JDK

> mvnd --version
mvnd native client 0.1.1-linux-amd64 (6e0a08b1700b4fa1278ae8734f895a598bca263b)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/***/mvnd-0.1.1-linux-amd64/mvn
Java version: 1.8.0_***, vendor: Oracle Corporation, runtime: ***
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-53-generic", arch: "amd64", family: "unix"

P.S. I would use mvnd even with no speedup because the build output is so improved!

**Comment by jjlharrison** [comment]
I'm seeing the same behaviour on Mac. Every run says that the daemon is either busy or incompatible.

**Comment by ppalaga** [comment]
Thanks for the report. Could you please briefly describe which `mvnd` commands you issue? Are you switching directories, possibly going to fully independent source trees? Do you see anything interesting in the log files under `.m2/mvnd/registry/*/`?

**Comment by ppalaga** [comment]
Thanks, I was able to figure out what is the problem. The fix is underway.
