### ISSUE TITLE
Maven-like rolling output when the build happens to be linear

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#269]
Originally discussed in https://github.com/mvndaemon/mvnd/issues/210.

In situations, when the build happens to be linear, because the dependency graph does not allow any concurrency, noBuffering could be activated automatically. (This is trivially true for single module builds)

@gnodet :

> It should be possible to enhance the smart builder to compute the maximum concurrency of a project, so that we could also use it as a maximum for the number of threads to display.

**Comment by gnodet** [comment]
I had work on computing the maximum width of the maven project, see https://github.com/gnodet/mvnd/commit/dadf524e13a8bd79cc245ccf22a2b8b5010e1742, but this can be part of a later enhancement to the automatic maven-like rolling output.
