### ISSUE TITLE
mvnd.rb not support mac now

### ISSUE THREAD

**Issue by oxsean** [mvndaemon/mvnd#273]
when run `brew upgrade` throws:

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mvndaemon/homebrew-mvnd/Formula/mvnd.rb
formulae require at least a URL

**Comment by gnodet** [comment]
It should be fixed with https://github.com/mvndaemon/homebrew-mvnd/commit/22a9c854943a5b2b143e94c123f094ad6f2427e6

**Comment by gnodet** [comment]
https://github.com/mvndaemon/homebrew-mvnd/issues/3
