### ISSUE TITLE
Status should indicate from which path the daemon was spawned

### ISSUE THREAD

**Issue by famod** [mvndaemon/mvnd#283]
I think it could be helpful if --status would include the path from which `mvnd` was first executed and thus spawned the daemon.

This could help with killing specific daemons and not all of them.

Btw, another improvement could be --status <UUID> to list more details like jvmArgs etc.

**Comment by ppalaga** [comment]
In case you mean the current working directory (PWD) from which the first `mvnd` command started the given daemon, then the answer is that PWD is a per-request property. In other words, one daemon can consecutively serve requests from different PWDs and there is nothing like PWD stored per-daemon in the registry.

**Comment by famod** [comment]
What if I pass jvmArgs? Or environment variables? Are those per request as well?

Please bear with me in case we already had this discussion. I lost track on recent improvements and fixes...

**Comment by ppalaga** [comment]
No problem at all, I am happy to explain :) 

> What if I pass jvmArgs? Or environment variables? Are those per request as well?

The answer is in `org.mvndaemon.mvnd.client.DaemonConnector.getCompatibleDaemons(Iterable<DaemonInfo>, DaemonCompatibilitySpec)` which is basically `JAVA_HOME` and a list of daemon opts. The daemon opts are assembled around [here](https://github.com/mvndaemon/mvnd/blob/master/daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java#L127-L129) from those `Environment` enum entries, which have `Flags.DISCRIMINATING` set. 

MVND_JVM_ARGS are discriminating https://github.com/mvndaemon/mvnd/blob/master/common/src/main/java/org/mvndaemon/mvnd/common/Environment.java#L208
For environment variables, it depends from whether the env. var is marked as discriminating in `Environment`. E.g. `MVND_NO_DAEMON` is https://github.com/mvndaemon/mvnd/blob/master/common/src/main/java/org/mvndaemon/mvnd/common/Environment.java#L149

**Comment by ppalaga** [comment]
It does not look like there is anything to fix here. Feel free to reopen if you think otherwise.
