### ISSUE TITLE
Enable some output per module or globally

### ISSUE THREAD

**Issue by rmannibucau** [mvndaemon/mvnd#292]
The issue I encouter is I know modules N1, N2, ...., N7 (i have 8 cores) are building but in test suite I have no idea what happens.
It can also be the case when some generation is long (I have the case with exec:java for ex but it can be with cxf or so).
Wonder if it would be possible to have last N output lines as well as the summary when running mvnd build?

3-4 line per module or ~10 lines of the overall output would work for me, idea is just really to see some progress to have an idea of what it does or why it hangs if it does.

**Comment by ppalaga** [comment]
At runtime, pressing `+` a couple of times might bring what you want. You can set [mvnd.rollingWindowSize](https://github.com/mvndaemon/mvnd/blob/master/common/src/main/java/org/mvndaemon/mvnd/common/Environment.java#L134-L139) in `~/.m2/mvnd.properties` to make it permanent.
We need to [document the key strokes supported by the client](https://github.com/mvndaemon/mvnd/issues/293) .

**Comment by rmannibucau** [comment]
@ppalaga thanks a lot, exactly what i was after.
