### ISSUE TITLE
Readme: "mvnd specific options" is incomplete

### ISSUE THREAD

**Issue by famod** [mvndaemon/mvnd#316]
It only lists `--status` and `--stop`. Ideally, it should always be in sync with the latest release. Maybe there is a file to link to?

**Comment by famod** [comment]
Probably related to #175. Maybe add a note that `mvnd --help` shows the full list, until #175 is resolved?

**Comment by ppalaga** [comment]
Yes, I'd vote for solving it properly once we have a docs site. And yes, in the meantime, we can advise to use mvnd --help
