### ISSUE TITLE
Execution of liquibase scripts is shown with level "error"

### ISSUE THREAD

**Issue by arnzel** [mvndaemon/mvnd#319]
When using mvnd the execution of liquibase migration scripts looks like this on the console

[ERROR] [stderr] INFO 08/01/2021, 14:02: liquibase: Successfully released change log lock

When using mvn it looks like this

INFO 08/01/2021, 14:04: liquibase: Successfully released change log lock

The job is executed successfully in both cases

**Comment by famod** [comment]
Liquibase used to be bad at logging which is why I used https://github.com/mattbertolini/liquibase-slf4j in older projects.
I'm not entirely sure about the most recent version 4, but `liquibase-slf4j` does seem to support it.

**Comment by ppalaga** [comment]
@arnzel could you please attach a simple reproducer?

**Comment by gnodet** [comment]
The culprit is this line: https://github.com/mvndaemon/mvnd/blob/5eaf9240e9d37895df79caaa778cf36ada59b8e5/daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java#L382

However, I'm not really sure I want it changed.  Printing to stderr is usually a really bad habit...

**Comment by ppalaga** [comment]
I thought it could also be caused by https://github.com/mvndaemon/mvnd/blob/5eaf9240e9d37895df79caaa778cf36ada59b8e5/agent/src/main/java/org/mvndaemon/mvnd/agent/Agent.java#L33 in a situation when stderr is redirected to stdin. A reproducer would help to see how liquibase is invoked and how it is logging.

**Comment by ppalaga** [comment]
@arnzel, any chance to provide a basic reproducer?

**Comment by arnzel** [comment]
@ppalaga  hi it cane reduced by

1. cloning repo https://github.com/jave/liquibase-helloworld
2. run mvnd liquibase:update

**Comment by gnodet** [comment]
Liquibase 3.0.0-rc1 is from 2013.  With a more recent version, the problem disappears.

**Comment by arnzel** [comment]
Yes , error disappears when updating to liquibase maven plugin version to >= 3.6.0

**Comment by ppalaga** [comment]
Thanks for confirming, @arnzel!
