### ISSUE TITLE
maven.compiler.source & maven.compiler.target 8

### ISSUE THREAD

**Issue by famod** [mvndaemon/mvnd#320]
These two properties are defined in root pom.xml, but shouldn't both be set to 11?
Furthermore, `maven.compiler.release` should be used instead, which also makes sure that you don't use JDK 12+ APIs.

**Comment by gnodet** [comment]
The client is >= 11, but the server needs to be compatible with JDK 8.

**Comment by famod** [comment]
Sorry for the late reply. My main point is that, ideally, the `mvnd` build process should make sure that for the Java8 parts no Java9+ API is used (or Java12+ for the Java11 parts).
I tried switching to `<release>8</release>` but this fails because of this Java9+ feature: https://github.com/mvndaemon/mvnd/blob/master/client/pom.xml#L94
Alternatively I could add [animal-sniffer-plugin](http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/examples/checking-signatures.html).

Is this topic of any interest @gnodet & @ppalaga?

**Comment by ppalaga** [comment]
> I tried switching to `<release>8</release>` but this fails because of this Java9+ feature: https://github.com/mvndaemon/mvnd/blob/master/client/pom.xml#L94

It is in the client and as @gnodet pointed out above, client's baseline is Java 11. Other modules should be Java 8+.

> My main point is that, ideally, the mvnd build process should make sure that for the Java8 parts no Java9+ API is used 

Yes, some sort of verification would be nice. Is animal-sniffer-plugin reasonably fast? Running the native integration tests on Java 8 would also be fine.

> (or Java12+ for the Java11 parts).

I think that's already guaranteed by the fact that we build with Java 11 on the CI. The build would fail if we used APIs from newer Java versions.

**Comment by famod** [comment]
> Is animal-sniffer-plugin reasonably fast?

I would say so. I'm using it in https://github.com/vackosar/gitflow-incremental-builder (which is a smaller project than `mvnd`, though). I can give it a try and post some numbers.

> I think that's already guaranteed by the fact that we build with Java 11 on the CI. The build would fail if we used APIs from newer Java versions.

Yeah, right, but it's always a bit frustrating if you think you're done (locally) just to see CI failing. 😉

**Comment by ppalaga** [comment]
> it's always a bit frustrating if you think you're done (locally), just to see CI failing after the push

I'd find it more frustrating to have slow local build :)

**Comment by famod** [comment]
I'll have a second, more detailed look at `<release>...</release>` and in case that doesn't work I'll give the sniffer a quicky try and report back.

**Comment by famod** [comment]
I've given up on this for now:

- `release` doesn't work in `client` due to:
  ```
  [ERROR] COMPILATION ERROR :
  [INFO] -------------------------------------------------------------
  [ERROR] exporting a package from system module java.base is not allowed with --release
  [INFO] 1 error
  ```
- `<release>8</release>` doesn't work in `daemon` due to:
  ```
  package sun.misc does not exist
  ```
  See also: https://stackoverflow.com/a/60172333/9529981 (which suggest adding an export, which would yield the same problem as in `client`)
  Maybe I'm wrong, but this smells like a toolchain and/or mutli-release jar problem.
- sniffer signatures only go as far as 1.8
