### ISSUE TITLE
Q: Any benchmarks?

### ISSUE THREAD

**Issue by theotherp** [mvndaemon/mvnd#334]
Do you have any benchmarks (of synthentic or real world scenarios) that show how much of a difference in performance mvnd makes? I tested it on two personal projects and couldn't really see any improvements. To be fair I just ran compile a couple of times and compared it with standard maven.

**Comment by gnodet** [comment]
Here's a simple test I just made:
 * first time compilation with maven (`mvn clean install -DskipTests`) => 9s
 * second time compilation with maven (`mvn clean install -DskipTests`) => 8s
 * first time compilation with mvnd (`mvnd clean install -DskipTests`) => 9s
 * second time compilation with mvnd (`mvnd clean install -DskipTests`) => 2.3s

Mvnd is all about reusing a daemon and caching, so the first time you use it for your project, you may not see much benefits.  This is particularly true for projects that contain a single module.  However, for big projects, `mvnd` does use parallel build by default, so you can see the time divided by 5 or more on the first time.

You'll find some more numbers at https://www.infoq.com/news/2020/12/mvnd-mavens-speed-daemon/

**Comment by theotherp** [comment]
For a proper comparison you have to use -T for the mvn call and use the
same amount of threads as mvnd.

**Comment by gnodet** [comment]
The parallel build has no effect when using a single build module, which I used in the first example.  Such builds do exercise the cache + JIT + native client improvements, and going from 8s to 2.3s sounds like a real improvement to me.

**Comment by gnodet** [comment]
The following is run on https://github.com/codehaus-plexus/plexus-io.git

Script:
```
function preexec() {
  cmd_start=$(($(print -P %D{%s%6.}) / 1000))
}

function precmd() {
  if [ $cmd_start ]; then
    local now=$(($(print -P %D{%s%6.}) / 1000))
    local d_ms=$(($now - $cmd_start))
    local d_s=$((d_ms / 1000))
    local ms=$((d_ms % 1000))
    local s=$((d_s % 60))
    local m=$(((d_s / 60) % 60))
    local h=$((d_s / 3600))

    if   ((h > 0)); then cmd_time=${h}h${m}m
    elif ((m > 0)); then cmd_time=${m}m${s}s
    elif ((s > 9)); then cmd_time=${s}.$(printf %03d $ms | cut -c1-2)s # 12.34s
    elif ((s > 0)); then cmd_time=${s}.$(printf %03d $ms)s # 1.234s
    else cmd_time=${ms}ms
    fi

    unset cmd_start
  else
    # Clear previous result when hitting Return with no command to execute
    unset cmd_time
  fi
}

preexec ; mvn -T1 clean install -DskipTests > /dev/null ; precmd ; echo "Maven 1: $cmd_time" ; \
preexec ; mvn -T1 clean install -DskipTests > /dev/null ; precmd ; echo "Maven 2: $cmd_time" ; \
preexec ; mvn -T1 clean install -DskipTests > /dev/null ; precmd ; echo "Maven 3: $cmd_time" ; \
preexec ; mvnd -T1 clean install -DskipTests > /dev/null ; precmd ; echo "Mvnd 1: $cmd_time" ; \
preexec ; mvnd -T1 clean install -DskipTests > /dev/null ; precmd ; echo "Mvnd 2: $cmd_time" ; \
preexec ; mvnd -T1 clean install -DskipTests > /dev/null ; precmd ; echo "Mvnd 3: $cmd_time"
```
Output:
```
Maven 1: 3.971s
Maven 2: 3.545s
Maven 3: 3.545s
Mvnd 1: 2.292s
Mvnd 2: 707ms
Mvnd 3: 603ms
```
