### ISSUE TITLE
Are you planning to support any GitHub Action to setup mvnd?

### ISSUE THREAD

**Issue by brusdev** [mvndaemon/mvnd#336]
Would be it advantageous to use mvnd in a GitHub Action saving the cache with [actions/cache](https://github.com/actions/cache)?

**Comment by gnodet** [comment]
`mvnd` does not use file caches, but in memory caches, so I don't think it can benefit from such a setup at the moment.

**Comment by brusdev** [comment]
@gnodet thanks for the prompt answer
