### ISSUE TITLE
Broken cache?

### ISSUE THREAD

**Issue by rmannibucau** [mvndaemon/mvnd#342]
Hi,

I'm not 100% sure how to reproduce the issue but I noticed that mvnd cache was using whereas it shouldn't.
Concretely I have a mojo listing compile+runtime (but not provided which is the important point) dependencies - project.getArtifacts + filtering.
At some point in the project a dependency was missing  the scope provided so I had like 10 dependencies listed, then it got fixed and I only kept 1 dependency listed.
This is the correct functional behavior.
However, after the fix and without restarting the daemon, mvnd was still listing the previous artifacts.

I didn't check/debug but I assume there are some caching issue somewhere (on transitive poms of the project?).

Side note: sorry to not be able to provide a reproducer but I needed to kill the daemon in between.

Romain

**Comment by gnodet** [comment]
Indeed, there are lots of caching done by maven and we try to be smart about what is invalidated by mvnd between runs...
Could you provide the mvnd version and your OS please ?

**Comment by rmannibucau** [comment]
Here it is:

```
$ mvnd --version
mvnd native client 0.2.0-linux-amd64 (0cd0b3f04692b7970fda06c206c1fbaac68fe9ce)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/rmannibucau/.sdkman/candidates/mvnd/0.2.0/mvn
Java version: 11.0.6, vendor: Azul Systems, Inc., runtime: /home/rmannibucau/.sdkman/candidates/java/11.0.6-zulu
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-38-generic", arch: "amd64", family: "unix"
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
```

**Comment by ppalaga** [comment]
0.2.0 is old. We did a lot of caching related changes since then. We released 0.4.1 yesterday. Could you plz. try with that one?

**Comment by rmannibucau** [comment]
Will upgrade, since I'm not sure of the cause I'm not sure I can give feedback quickly but if it occurs again i will come back. Thanks for the quick feedback.

**Comment by rmannibucau** [comment]
Didnt get this error again so guess we should close it.
