### ISSUE TITLE
--quiet seems to supress mvn output entirely in some cases

### ISSUE THREAD

**Issue by pgutierrezn2** [mvndaemon/mvnd#344]
Although [pull request #90](https://github.com/mvndaemon/mvnd/pull/90) helps _honor the -X / --debug / --quiet arguments on the command line_ I've found some differences regarding --quiet. It seems to suppress mvn output entirely in some cases

The following examples invoke _maven-help-plugin:3.2.0:evaluate_ to obtain the _groupId_ of an artifact.

> [web@dljenci1 j15-01i-ear]$ /SRV/TOOLS/mvnd-0.4.1-linux-amd64/bin/mvnd -T1  org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate  -Dquickly -Dexpression=project.artifactId  -DforceStdout -Djava.io.tmpdir=/SRV/website/temporal/jenkins -q
> [INFO] BuildTimeEventSpy is registered.
> [INFO] Task segments : [org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate]
> [INFO] Build maximum degree of concurrency is 1
> [INFO] Total number of projects is 1
> [INFO] Segment walltime 0 s, segment projects service time 0 s, effective/maximum degree of concurrency 0,66/1

While normal maven output is just the groupId: "j15-01i-ear"

> [web@dljenci1 j15-01i-ear]$ /SRV/TOOLS/apache-maven-3.6.3/bin/mvn  org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dquickly -Dexpression=project.artifactId  -DforceStdout -Djava.io.tmpdir=/SRV/website/temporal/jenkins -q
> j15-01i-ear

**Comment by gnodet** [comment]
In this very case, the fact that the property is not displayed comes from the fact that the stdout is intercepted and sent to the client when a newline is detected.  The `evaluate` does not print one.
