### ISSUE TITLE
mvnd assumes an .m2 folder in home directory

### ISSUE THREAD

**Issue by JSamir** [mvndaemon/mvnd#360]
Hi,

since I like to keep my home folder clean, I have changed the maven config according to this site: https://wiki.archlinux.org/index.php/XDG_Base_Directory

This way, I've got my settings.xml file in `~/.config/maven/settings.xml`. Within my `settings.xml` file I've got this:
```
<localRepository>${env.XDG_CACHE_HOME}/maven/repository</localRepository>
```

With this aliases this works fine:
```
alias mvn="mvn -gs $XDG_CONFIG_HOME/maven/settings.xml"
alias mvnd="mvnd -gs $XDG_CONFIG_HOME/maven/settings.xml"
```

Except for the fact that `mvnd` is still creating some files in the `.m2` folder:
```
❯ ls -l ~/.m2/mvnd/registry/0.4.1/
total 8784
-rw-r--r-- 1 samir samir 6292122 Feb 15 17:32 daemon-244f1c67.log
-rw-r--r-- 1 samir samir       0 Feb 15 16:12 daemon-244f1c67.out.log
-rw-r--r-- 1 samir samir 2682989 Feb 12 19:56 daemon-6db22e38.log
-rw-r--r-- 1 samir samir       0 Feb 12 16:53 daemon-6db22e38.out.log
-rw-r--r-- 1 samir samir    2498 Feb 12 16:53 purge-2021-02-12.log
-rw-r--r-- 1 samir samir     266 Feb 15 16:12 purge-2021-02-15.log
-rw-r--r-- 1 samir samir   32768 Feb 15 17:24 registry.bin
```

**Comment by gnodet** [comment]
Try with
```
alias mvnd="mvnd -Dmvnd.daemonStorage=$XDG_CONFIG_HOME/mvnd -gs $XDG_CONFIG_HOME/maven/settings.xml"
```

**Comment by JSamir** [comment]
Thanks, works.

Although I am not exactly sure if this should go in `.config` or rather `.cache` directory.

Maybe you could consider adapting the defaults to the XDG standards?
