### ISSUE TITLE
Hangs after dumping all the Maven output on WSL1

### ISSUE THREAD

**Issue by famod** [mvndaemon/mvnd#363]
`mvnd` seems to hang (mostly forever) after dumping the entire Maven output, after the build has succeeded. The output does look complete.

I don't get this in WSL2 on my private PC, but on WSL1 on my work laptop. I did also have a few non-hanging runs, but not in the last days.

`jstack` on the daemon side looks rather uneventful to me:
[jstack1.log](https://github.com/mvndaemon/mvnd/files/5989897/jstack1.log)
[jstack2.log](https://github.com/mvndaemon/mvnd/files/5989898/jstack2.log)

Interestingly, `mvnd --status` in another shell hangs as well.
`mvnd --help` manages to print everything until ` string                                 A string`, but then hangs as well.

**Comment by famod** [comment]
Even more strangley, killing the daemon java process does _not_ unblock the clients.

**Comment by gnodet** [comment]
If you can reproduce the problem, can you check if hitting the enter key unblocks the client ?

**Comment by famod** [comment]
I don't use WSL1 anymore and there have been many mvnd update since I created this issue so I will close this.
