### ISSUE TITLE
autokill if inactive since some time + memory becomes low?

### ISSUE THREAD

**Issue by rmannibucau** [mvndaemon/mvnd#364]
Hi,

It is common to let mvnd "leak" (it is designed for that right? ;)) but when working on other builds which take a lot of memory using mvn and not mvnd it can eat too much memory (typically the case running graal native-image in the build) - in my case mvnd was eating something around 3G.

I wonder if a condition/scheduled task to kill the daemon if inactive since some minimum time (10mn?) and memory becomes too low (85% or so of the system?) would be beneficial?

Hope it makes sense.

Romain

**Comment by gnodet** [comment]
I think we already have a quite complex strategy in place:
  https://github.com/mvndaemon/mvnd/blob/ddea5d8ea8b113ee5690ed68fd7d35d5f944e01f/daemon/src/main/java/org/mvndaemon/mvnd/daemon/DaemonExpiration.java#L53-L60

**Comment by gnodet** [comment]
Your exact use case could be covered by the `lowMemory` but it has not been implemented.  I think it requires native functions to access the system memory stats somehow.

**Comment by JanecekPetr** [comment]
> I think it requires native functions to access the system memory stats somehow.

It does, indeed. The tool I've used for similar tasks before is https://github.com/oshi/oshi. The downside is that it's a 800kB library, so perhaps a less heavy (but more brittle) way would be to call an OS-specific command. Linux and Unix have `free`, Windows has [`wmic ComputerSystem get TotalPhysicalMemory`](https://superuser.com/questions/315195/is-there-a-command-to-find-out-the-available-memory-in-windows).

**Comment by rmannibucau** [comment]
sigar library would work as well and is quite easy to setup (as you know ;))

**Comment by gnodet** [comment]
If it's only a couple of native functions, they could be added to jansi.

**Comment by gnodet** [comment]
Depends on #400
