### ISSUE TITLE
Keep daemon alive in Docker?

### ISSUE THREAD

**Issue by lanmaoxinqing** [mvndaemon/mvnd#365]
Hi,

In mvnd, daemon thread is started by client thread "xxx/bin/mvnd".  onces build finished, the client thread will release but leaves daemon thread keep alive in phyical machine, while in docker, daemon thread will be killed when parent thread is finished.

When another client thread triggered, it tries to get the last daemon thread which was killed, and ends with "No message received within 3000ms, daemon may have crashed. You may want to check its status using mvnd --status" exception.

Thus No more mvnd builds can be done since then.

**Comment by gnodet** [comment]
I don't fully understand.  Could you give exact steps to reproduce the problem ?  The daemon process is meant to survive the client `mvnd` call, that's the whole point of mvnd.

**Comment by lanmaoxinqing** [comment]
> I don't fully understand. Could you give exact steps to reproduce the problem ? The daemon process is meant to survive the client `mvnd` call, that's the whole point of mvnd.

Hi gnodet,
Sorry for my poor english, i retried mvnd run in a simple docker image, and then the daemon thread keeps alive.
In produce environment, we run `mvnd` cmd in our own script which use the same thread group with parent thread, that's the root reason why daemon thread is killed. 

This issue can be closed now :-)
