### ISSUE TITLE
Global mvn settings.xml via mvnd.properties

### ISSUE THREAD

**Issue by mgoldschmidt-ds** [mvndaemon/mvnd#383]
Hi there, just found this project and gave it a try (and fell in love already).

OS: Windows 10
mvnd: mvnd-0.4.3-windows-amd64

Having multiple local mvn setups (not using mvnw) I use multiple settings.xml for each as well. E.g. configure different local repositories or mirrors. Therefore each mvn is configured with its specific global settings.xml on my machine.

Having found "mvnd-0.4.3-windows-amd64\mvn\conf\settings.xml" I tried the same and modified this file but mvnd.exe seems to ignore any change on it:
`mvnd-0.4.3-windows-amd64\bin\mvnd.exe -X -ff `
still calls maven central for example despite the fact I set a mirror in settings.xml

`mvnd-0.4.3-windows-amd64\bin\mvnd.exe -X --ff -s "mvnd-0.4.3-windows-amd64\mvn\conf\settings.xml" `
works but is quite cumbersome to configure.

Is there any possibility to provide the path to global settings.xml within e.g. mvnd.properties as well?
I did not find any clue within the provided file or help by now.

Thank you for your time!
Regards Michael

**Comment by ppalaga** [comment]
Does adding 

```
maven.settings = /path/to/settings.xml
```

to `~/.m2/mvnd.properties` solve your problem?

**Comment by mgoldschmidt-ds** [comment]
Oh my god, the world could be so simple ;) Thanks @ppalaga your proposal brought me on the right track.

` ~/.m2/mvnd.properties` is no option for me because then I need to update this file every time I switch my project setup.

But to solve this I am able to set `maven.settings = /path/to/settings.xml` (maven style in windows) within "mvnd-0.4.3-windows-amd64\conf\mvnd.properties" and it works as expected.

Give me a view days and I will review the details and provide some input for the README on this.

Thank you very much!

**Comment by mgoldschmidt-ds** [comment]
Just proposed a PR to provide more details which would have helped me on this.
Feel free to review and merge if ok. Or leave a comment and I'll try to fix. Thanks in advance.
