### ISSUE TITLE
${my.property:-default} style defaults defined in logback.xml do not work

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#39]
I wanted to add something like the following to logback.xml, but it does not work

```
  <!-- Allow increasing mvnd log level from command line -->
  <logger name="org.jboss.fuse.mvnd" level="${mvnd.log.level:-INFO}" />
```

With the above setting and `-Dmvnd.log.level=DEBUG` passed via CLI, the log level is not set to `DEBUG`.

When I change it to
```
  <logger name="org.jboss.fuse.mvnd" level="${mvnd.log.level}" />
```

`-Dmvnd.log.level=DEBUG` works as expected, but building without `-Dmvnd.log.level=DEBUG` (as expected per logback docs) leads to `org.jboss.fuse.mvnd` being set to `DEBUG` anyway, which is not nice.

**Comment by gnodet** [comment]
That may have been fixed by https://github.com/mvndaemon/mvnd/commit/59a9bbad5b98889faa7e8154c65bee1e10cd9f6f

**Comment by gnodet** [comment]
I found what is happening.  The daemon JVM is launched first without any specific system properties from the command line, so when the logback configuration is loaded, the `mvnd.log.level` is not set.
The workaround is to use `mvnd.jvmArgs="-Dmvnd.log.level=DEBUG"` in one of the `mvnd.properties` file or on the command line using `-Dmvnd.jvmArgs="-Dmvnd.log.level=DEBUG"`.  Note that the `mvnd.jvmArgs` is a discriminating property, so a specific daemon will be created.
