### ISSUE TITLE
Support Maven 3.8.1

### ISSUE THREAD

**Issue by robertklaus-bosch** [mvndaemon/mvnd#393]
Maven 3.8.1 has been released with some fixes for CVEs:
https://maven.apache.org/docs/3.8.1/release-notes.html

Would it be possible to support this?

**Comment by ppalaga** [comment]
Yes, definitely. Somebody just has to find a couple of free cycles for that :)

**Comment by robertklaus-bosch** [comment]
Let me guess, there is more to do than bumping up the ```maven.version``` in the pom.xml 😉 
Any pointers what would need to be done for this?

**Comment by ppalaga** [comment]
It's bumping and seeing what got broken 8-)

**Comment by robertk3s** [comment]
Damn. Check on darwin fails with compilation error. Could need a hint what went wrong here.

**Comment by ppalaga** [comment]
> Damn. Check on darwin fails with compilation error. Could need a hint what went wrong here.

The error message sounds like some variant of https://github.com/mvndaemon/mvnd/issues/281 I have restarted the jobs to see if it happens again.

**Comment by robertk3s** [comment]
@ppalaga thanks for the support. Restarting the checks helped, they passed now!

**Comment by robertk3s** [comment]
@ppalaga , @gnodet how are we going to proceed with this now?

**Comment by robertk3s** [comment]
@gnodet wrote on the puill request:
> Given 3.8.1 creates some incompatibilities, I'd really like to get the time to work on supporting multiple maven versions as indicated by #143 .

I can totally understand the wish to support multiple versions. I'm not so experienced with GitHub Actions, just thinking that basically it is possible to set the Maven version with -Dmaven.version and do the build again (+ setting a version on the binaries).
Might be doable with this maybe:
https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps/ ?

Or the simply a branch with the 3.6.x and one with the 3.8.x .. that would be simple, but has some disadvantages of course. 

What do you think?

**Comment by gnodet** [comment]
> @gnodet wrote on the puill request:
> 
> > Given 3.8.1 creates some incompatibilities, I'd really like to get the time to work on supporting multiple maven versions as indicated by #143 .
> 
> I can totally understand the wish to support multiple versions. I'm not so experienced with GitHub Actions, just thinking that basically it is possible to set the Maven version with -Dmaven.version and do the build again (+ setting a version on the binaries).
> Might be doable with this maybe:
> https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps/ ?
> 
> Or the simply a branch with the 3.6.x and one with the 3.8.x .. that would be simple, but has some disadvantages of course.
> 
> What do you think?

Yes, I'm now thinking that's the best way forward.
