### ISSUE TITLE
Cannot clean on Windows as long as mvnd keeps a plugin from the tree loaded

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#40]
Reproducible by adding `clean` to the second invocation of `client.execute()` in `ModuleAndPluginNativeIT`. 

This is because the test project uses a plugin which is compiled from sources in the same source tree. Windows does not allow deleting open file, so as long as mvnd keeps the plugin jar open, it cannot be cleaned/deleted.

**Comment by gnodet** [comment]
We should improve the `CliPluginRealmCache` to get rid of realms for plugins build in the reactor after (or before) a project build somehow.

**Comment by ppalaga** [comment]
Yeah, I thought of that too.
