### ISSUE TITLE
use unix domain socket if available

### ISSUE THREAD

**Issue by homberghp** [mvndaemon/mvnd#417]
I would like to run maven builds with a user who has no network access. 

- Access is disabled with iptables suppressing all  network access with iptables -A OUTPUT -p all -m owner --uid-owner 1002 -J DROP.
- Purpose is to build untrusted code (actually student code, but we want to make any fraud as difficult as possible, so disable network during build to disable access to trojans and such)
Maybe open just the mvnd ports will do.

**Comment by gnodet** [comment]
It should be possible to compile the client code using GraalVM on JDK 16 and defaulting to using unix sockets when building on JDK 16.

**Comment by gnodet** [comment]
The ipc sync server should also be enhanced to use unix domain socket.

**Comment by electrum** [comment]
For reference: https://inside.java/2021/02/03/jep380-unix-domain-sockets-channels/
