### ISSUE TITLE
Parallel build fails due to missing JAR artifacts in compilePath

### ISSUE THREAD

**Issue by lanmaoxinqing** [mvndaemon/mvnd#418]
Maven-compiler-plugin lost the compilePath param when running multi projects concurrently.
Can be reproduced by
https://github.com/fkalinski/parallel-testbed

It seems to be a maven bug, and has not been resolved in latest maven (3.8.1)
https://issues.apache.org/jira/browse/MNG-6843

thanks to @famod , there's a workaround, and I wonder if we should fix it in mvnd or wait for a maven further resolution.
https://github.com/apache/maven/pull/413

I see your discussion in https://github.com/apache/maven/pull/413, hoping we can make a conclusion soon.

**Comment by gnodet** [comment]
I'm going to add the fix outlined in https://github.com/apache/maven/pull/413 in `mvnd` until we can get it fixed in maven itself.
