### ISSUE TITLE
GitHub workflow: Cache dependencies

### ISSUE THREAD

**Issue by helpermethod** [mvndaemon/mvnd#426]
Hi,

is there a reason that the workflow doesn't cache Maven dependencies between runs? Pretty sure it would shave off 3-4 min per run.

**Comment by ppalaga** [comment]
I find downloading of deps an important part of Maven's and mvnd's functionality that should not not be faked during testing. If we cache deps we may prevent ourselves from seeing many kinds of issues that have to do with concurrent reading/writing to local Maven repo.

**Comment by helpermethod** [comment]
Thanks for answering, that makes sense!
