### ISSUE TITLE
Provide a `mvnd.daemon` option to disable daemon for easier debugging

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#43]
It would be useful if we could skip the client/server stuff to more easily debug the daemon.

**Comment by ppalaga** [comment]
How would you implement that given that the native client cannot load classes at runtime? Would that be an option of the existing mvnd shell script? Or perhaps a new script calling the daemon.jar directly?

**Comment by gnodet** [comment]
The option could be only available for the non native client.  The goal is to more easily debug the server side build, so the client is not really important in the scenario.

I've pushed a draft commit I did some time ago, but it wasn't working fully, so that's just an idea : https://github.com/gnodet/mvnd/tree/issue-43

**Comment by ppalaga** [comment]
Makes sense, thanks for the explanation.
