### ISSUE TITLE
Incorrect charset display in Terminal output

### ISSUE THREAD

**Issue by lanmaoxinqing** [mvndaemon/mvnd#441]
When the `locale` variable in system env is not `UTF-8` ( e.g. `GB18030` ) , mvnd do not print message correct into console using `TerminalOutput`, but  something like below
```
[ERROR] /workspace/code-repo/app/core/service/src/main/java/systems/RuntimeService.java:[26,54] ??GBK???????

[ERROR] /workspace/code-repo/app/core/service/src/main/java/systems/RuntimeService.java:[26,73] ??GBK???????

[ERROR] /workspace/code-repo/app/core/service/src/main/java/systems/RuntimeService.java:[31,20] ??GBK???????
```

cause we did not set the `encoding` param in constructor
```java
    public TerminalOutput(boolean noBuffering, int rollingWindowSize, Path logFile) throws IOException {
        this.start = System.currentTimeMillis();
        this.terminal = TerminalBuilder.terminal(); <-- here
        this.dumb = terminal.getType().startsWith("dumb");
        this.noBuffering = noBuffering;
...
```

one thing more, `graalvm` does not support `ExtendedCharsets` by default in linux according to https://github.com/oracle/graal/issues/1294#issuecomment-492915082, so we need to add the `-H:+AddAllCharsets` param when generating the native image.

I will commit a PR for this issue later.

**Comment by gnodet** [comment]
@lanmaoxinqing I do agree with the change related to graalvm, but I don't understand the explicit parsing of the `LANG` environment variable.  If not provided explicitly, jline should use the default charset.  Is that one wrong too ?  That should mean that any string written using `System.out.println()` should fail too... ?

**Comment by lanmaoxinqing** [comment]
>  If not provided explicitly, jline should use the default charset. Is that one wrong too ?

You are right. The change related of `LANG` can be ignored, cause this is our private projects workaround and should not be a standard solution.

This is a trick fix for inexplicit encoding in maven-resources-plugin. When resources are `GB18030` and no `project.build.sourceEncoding` is provided, we use `LANG` environment variable to make it correct, and i apply it to `jline` too.

I will glad to remove this.

**Comment by gnodet** [comment]
@lanmaoxinqing that would be nice, I'll gladly apply the PR when you remove the `LANG` stuff.
