### ISSUE TITLE
Use custom wrapper

### ISSUE THREAD

**Issue by Steph0** [mvndaemon/mvnd#455]
Hi there,

First, thanks for the work with mvndaemon.
There is something I can't figure out from the documentation. My project already has a maven wrapper. And i'd like mvndaemon to use my wrapper or at least setup mvndaemon to download the same version that my project uses.

What is the config to do. Note that I installed using sdkman.

If I get the answer here, i'll do a pull request to offer a documentation about it :)

**Comment by Steph0** [comment]
I saw that: https://github.com/mvndaemon/mvnd/issues/143 
I find that it is a huge missing feature that makes mvnd less interesting to use.
It could be nice at least to have a list of supported maven version (like sdkman) and be able to use this list of supported versions. :)

**Comment by ppalaga** [comment]
A given mvnd version is hardwired to some particular version of Maven core libs. Those embedded in mvnd's own distro. Mvnd is not using any existing local Maven installation.
To make mvnd use some specific version of Maven core libs, you need to figure out which mvnd version is using your desired Maven core libs version and then stick to that mvnd version. 

Of course this does not solve the problem Maven Wrapper solves - i.e. to have a reliable per-repo way of choosing the mvnd version that is known to be suitable for building of the given repo. For that one, having our own `mvndw` script that would pull a specific version of `mvnd` (contributions welcome!) still seems to be the most viable solution to me.

**Comment by Steph0** [comment]
Thanks @ppalaga but how to find the mvnd that contains a given version ? For example i'm searching the one for mvn 3.5.0

The tagging system on the repo does not indicate it

**Comment by ppalaga** [comment]
> how to find the mvnd that contains a given version

Only manually in `org.mvndaemon.mvnd:mvnd`'s pom: https://github.com/mvndaemon/mvnd/blob/master/pom.xml#L48

> I'm searching the one for mvn 3.5.0

I am afraid the oldest one we ever had in the source tree was 3.6.2 and the oldest release was with 3.6.3

**Comment by Steph0** [comment]
Forgot to answer due to vacation but thank you for your answers! :)
I think that settles my question
