### ISSUE TITLE
Support Maven 3.8.2

### ISSUE THREAD

**Issue by robertk3s** [mvndaemon/mvnd#457]
Maven 3.8.2 is available with a bunch of bug fixes.
See announcement + release notes here:
http://maven.apache.org/docs/history.html

**Comment by robertk3s** [comment]
Sorry first pr was bogus :/

**Comment by gnodet** [comment]
Maven 3.8.2 has some nasty issues (see https://issues.apache.org/jira/browse/MNG-7216), so I'd rather skip that one and defer the upgrade to 3.8.3.
