### ISSUE TITLE
release 0.5.3?

### ISSUE THREAD

**Issue by rmannibucau** [mvndaemon/mvnd#473]
Hi,

Is it possible to get 0.5.3 please (I'm particularly interested in sdkman flavor)?
I'd like to get the early error reporting.

Thanks a lot
Romain

**Comment by ppalaga** [comment]
We released 0.6.0 yesterday

**Comment by rmannibucau** [comment]
oops, mea culpa, :+1: and thanks again for the hard work!

**Comment by ppalaga** [comment]
No problem at all! 

To get notified, you may want to follow https://twitter.com/mvndaemon or watch this repo for release events 
![image](https://user-images.githubusercontent.com/1826249/132483311-49b6862a-fcb3-424a-93e3-767e70b090d1.png)
