### ISSUE TITLE
List mvnd on sdkman.io

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#48]
Citing @gastaldi:

> it would be nice to have it listed in sdkman.io

Volunteers?

**Comment by helpermethod** [comment]
Hi, would love to help out!

**Comment by ppalaga** [comment]
Thanks, @helpermethod !

**Comment by marc0der** [comment]
This certainly looks doable, but would require standard application zip archives to be built for each platform. This could be done using the maven assembly plugin (as the project seems to be built with maven).

**Comment by helpermethod** [comment]
If it's okay for @ppalaga I could add the missing build step.

**Comment by ppalaga** [comment]
Yes, of course, adding maven assembly plugin is OK.

The question is whether we should keep publishing the plain (non-zipped) mvnd client executables on GH releases as we do today?

The unzipped mvnd client executables might be seen as easier to install for the people who do not want or can't use sdkman. OTOH, installing from the zipped ones is just one step more to document in the README. What do others think?

**Comment by ppalaga** [comment]
> The question is whether we should keep publishing the plain (non-zipped) mvnd client executables on GH releases as we do today?

That's actually related but separate issue. We do not need to solve it here. But for the record: I would not mind if we stop publishing the non-zipped clients.

**Comment by helpermethod** [comment]
The native image is now packaged into a ZIP archive. Wasted endless hours trying to make the `provision-maven-plugin` work but finally gave up and used the `maven-assembly-plugin` 😭 .

I've also added additional steps to the GitHub workflow.

**Comment by ppalaga** [comment]
The zip files in https://github.com/mvndaemon/mvnd/releases/tag/0.0.3 should comply with the requirements of sdkman. What do we need to do next?

**Comment by helpermethod** [comment]
Hi, a PR for a DB migration needs to be created at https://github.com/sdkman/sdkman-db-migrations.

**Comment by helpermethod** [comment]
Hi @ppalaga,

got a little bit time today and will add mvnd to SDKMAN! as a candidate.

**Comment by helpermethod** [comment]
Hi @ppalaga,

the PR got successfully merged, sorry for waiting so long.

Looking good so far

![image](https://user-images.githubusercontent.com/1562019/92097529-77644400-edd8-11ea-9e12-8bc5000a4b9f.png)
![image](https://user-images.githubusercontent.com/1562019/92097684-a975a600-edd8-11ea-84dd-e7e0b60ae499.png)

**Comment by helpermethod** [comment]
On Mac OSX, it seems to be working but

![image](https://user-images.githubusercontent.com/1562019/92098143-2d2f9280-edd9-11ea-8201-df301958184d.png)

**Comment by helpermethod** [comment]
BTW future versions of `mvnd` could be published via the [Vendor API](https://sdkman.io/vendors).

`JBang` and others do this too.

**Comment by helpermethod** [comment]
Hi @ppalaga,

not sure if this is related to the way SDKMAN! installs `mvnd` but on my Mac `mvnd` is not able to ever reuse a daemon

![image](https://user-images.githubusercontent.com/1562019/92234676-c088c680-eeb2-11ea-9618-9af5290788fa.png)

**Comment by helpermethod** [comment]
Hi @ppalaga, can we close this?

**Comment by ppalaga** [comment]
Great work, thanks @helpermethod !
