### ISSUE TITLE
Windows+Cygwin - Why do I get weird output?

### ISSUE THREAD

**Issue by snillocbor** [mvndaemon/mvnd#483]
I was happily using mvnd, then in 0.5 I started getting weird stuff mixed into my output. Tried 0.6.0 and still seeing it.

What can I do to make this stop?

$ mvnd -help
←[1mLooking up daemon...←[0m  time: ←[1m00:01←[0m
←[A←[1mConnected to daemon cc0e937f, scanning for projects←[0m←[17P←[1m...←[0m  time: ←[1m00:01←[0m
←[A←[K[←[1;33mWARN←[m] A few environment mismatches have been detected between the client and the daemon.
[←[1;33mWARN←[m]    PWD -> /cygdrive/c/Users/rcoll/dev/src/core instead of C:\Users\rcoll\dev\src\core
[←[1;33mWARN←[m] If the difference matters to you, stop the running daemons using mvnd --stop and
[←[1;33mWARN←[m] start a new daemon from the current environment by issuing any mvnd build command.

usage: mvnd [options] [<goal(s)>] [<phase(s)>]

Options:

**Comment by gnodet** [comment]
See https://github.com/jline/jline3/issues/669

**Comment by snillocbor** [comment]
Thanks for the pointer. I was able to resolve my issue by unsetting PWD environment variable before starting the mvnd client.
