### ISSUE TITLE
Different java versions for mvnd and maven

### ISSUE THREAD

**Issue by gandadil** [mvndaemon/mvnd#512]
I am trying to compile a Java 7 source with mvnd but it's not supported. If there is any way to set different JAVA_HOME for mvnd and internal maven I can run mvnd with Java 11 for example and maven with Java 7. Is it possible?
I tried set java.home with Java 11 on mvnd.properties and JAVA_HOME with Java 7 but doesn't work.

**Comment by khmarbaise** [comment]
You can use JDK11 runtime for all and set the `--release 7` which produces JDK7 compatible code. mvnd itself needs at minimum JDK8 to run...

**Comment by gandadil** [comment]
Unable to parse command line options: Unrecognized option: --release

**Comment by khmarbaise** [comment]
This means you are running with JDK8 or less...that does not work. The `--release´ is available from JDK9+ As I said run your build with JDK11 and use the --release option..

**Comment by gnodet** [comment]
Reopen if needed.

**Comment by gandadil** [comment]
Well, I am using Semeru distribuition of Adoptium OpenJDK 11 and is receiving this message. Maybe I need to use a distribution with Hotspot JVM instead OpenJ9?

**Comment by gnodet** [comment]
The `--release 7` is a java compiler option, not a `mvnd` option.  This option needs to be configured on the maven compiler plugin.  Also make sure your `JAVA_HOME` environment variable points to a JDK that does support java 7.
