### ISSUE TITLE
Using MAVEN_HOME may clash with other tools

### ISSUE THREAD

**Issue by OPeyrusse** [mvndaemon/mvnd#53]
As part of the installation process [1], the last command is to run `mvnd --install`.
This is returning the following error:
> Exception in thread "main" java.lang.IllegalStateException: Cannot install if mvnd.home /opt/sdkman/candidates/maven/current exists. Delete it if you want to reinstall.
	at org.jboss.fuse.mvnd.client.Installer.installServer(Installer.java:55)
	at org.jboss.fuse.mvnd.client.DefaultClient.install(DefaultClient.java:98)
	at org.jboss.fuse.mvnd.client.DefaultClient.execute(DefaultClient.java:152)
	at org.jboss.fuse.mvnd.client.DefaultClient.main(DefaultClient.java:68)

The reported directory is my current installation. It seems that this happens because the variable `MAVEN_HOME` is set in my environment.

I see that `mvnd --install` created a bin directory under _.m2/mvnd/\<version>_. But I don't understand why the failure, particularly as MAVEN_HOME is a variable for maven1, and mvnd claims to be a maven 3+.

Can you explain the reason for such a design? As I plan to call `mvnd` explicitly instead of `mvn`, I don't want to enforce a path to the provided maven script.

[1] https://github.com/mvndaemon/mvnd#install-mvnd

**Comment by ppalaga** [comment]
Thanks for the report, I think this is a valid issue. We better should not mess with `MAVEN_HOME` that can be set/used by other tools with incompatible design. I think we should switch to `MVND_HOME` and `mvnd.home`. WDYT, @gnodet ?

**Comment by ppalaga** [comment]
Also note that we are about to make mvnd installable by sdkman in https://github.com/mvndaemon/mvnd/issues/48. Solving that probably requires to solve this too.

**Comment by OPeyrusse** [comment]
That's really cool. I have checked that issue 5 days ago but did not found an easy tutorial on how to do it so I let it pass by.
I can help in any way, do tell me.

**Comment by OPeyrusse** [comment]
Many thanks. Waiting for the next release, apparently in sdkman :rocket:
