### ISSUE TITLE
Question: is there a way to limit the concurrency?

### ISSUE THREAD

**Issue by orpiske** [mvndaemon/mvnd#59]
When I run `mvnd` it consumes all cores on my machine and that's usually great. However, sometimes I wish I could adjust how many cores it could use.

I know maven has the `-T<num>C` option, but it does not seem to work for `mvnd`. Is there a way I could do that?

**Comment by ppalaga** [comment]
Passing `-TnC` via CLI should work and if it does not, it is a bug.

Here https://github.com/mvndaemon/mvnd/blob/master/client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java#L227-L229 the intention was to pass `-T1C` to the server only if `-TnC` was not specified by the user.

**Comment by orpiske** [comment]
> Passing `-TnC` via CLI should work and if it does not, it is a bug.
> 
> Here https://github.com/mvndaemon/mvnd/blob/master/client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java#L227-L229 the intention was to pass `-T1C` to the server only if `-TnC` was not specified by the user.

Thanks Petr. The `-T<num>C` did the trick, indeed. When I had tried it earlier I haven't realized I had passed the option to -T incorrectly (I forgot the C) which led me to believe `mvnd` did not accept it. 

Thanks for clarifying it!
