### ISSUE TITLE
Question: when running mvnd, it looks like regular mvn is still running

### ISSUE THREAD

**Issue by Keso-Rupert** [mvndaemon/mvnd#60]
Hi!
This looks like a really cool project and I'm excited to try it out. However after following the instructions to installing, I still get this output when running mvnd --version:

```
 ✘ kesorupert  ~  mvnd --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_262, vendor: AdoptOpenJDK, runtime: /Users/kesorupert/.sdkman/candidates/java/8.0.262.hs-adpt/jre
Default locale: en_NL, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
```

I added the mvn daemon bin folder to my PATH variable. I also tried using an alias for mvnd that pointed specifically to the mvnd executable inside the bin folder.
I'm using Oh-my-ZSH, so I thought that there maybe was some correcting going on, but disabling that using "nocorrect" and other options, all resulted in the same output. 

Any idea on what I'm missing when setting this up?

**Comment by ppalaga** [comment]
That's really strange. Could you perhaps try what is the output of `mvnd -v` in a different shell, such as bash? 

What happens if you run /absolute/path/to/mvnd -v`?

You may also try running `which mvnd` or its equivalent of your shell to see which absolute path is resolved for `mvnd`.

**Comment by Keso-Rupert** [comment]
Thanks for your quick reply! I used which mvnd and saw that my mvn Oh my zsh plugin was aliasing mvnd to mvn deploy... I unaliased it in my .zshrc file and now Maven Daemon works fine! Cut my building time from 14 seconds to 6, so that's very cool! Thanks!

**Comment by ppalaga** [comment]
Happy to hear that!
