### ISSUE TITLE
Explain project better in README

### ISSUE THREAD

**Issue by IvoLimmen** [mvndaemon/mvnd#75]
Hi, 

I am a developer and saw the annoucement on SDKMAN on this project. I clicked the link as I am a fond maven user and your project sounded interesting. Your readme describes only:

`The mvnd project aims to provide a daemon infrastructure for maven based builds. It borrows techniques from Gradle and Takari to provide a simple and efficient system.`

Provide daemon infrastructure: what does that mean in practicle sense? Does it make my builds go faster? Does it cache stuff? I have no idea if I want (or NEED) to check this out..

Could you provide some nice markteting slur somewhere in the README to entice me more?

**Comment by ppalaga** [comment]
Thanks for the report. Yes, there is a lot of potential to make that that paragraph more informative. Let's work on that.
