### ISSUE TITLE
Show test output while running

### ISSUE THREAD

**Issue by blsouthr** [mvndaemon/mvnd#77]
Currently test output it showed **after** all tests are run. If one have lots of tests, its useful to see what is going on while running tests and possibly interrupt the build early if some test fails. This would save lot of time and on failures and provide the status of build while it running.

Right now, one have always wait until the end of mvnd build to see if some tests failed.

**Comment by gnodet** [comment]
We could have such an option when running in a single threaded build.  In a multithreaded build, the output is mixed between the various modules.  In those cases, we could allow displaying the build log for processed modules.

Another option would be to have a small log window for each module, i.e. display the last 3 lines of the log for each module being processed below the current line for the module.

**Comment by blsouthr** [comment]
That would be awesome.

**Comment by blsouthr** [comment]
@gnodet Just installed v0.0.8 via sdkman and it still not showing the output while running the tests

Maven Daemon 0.0.8-linux-amd64 (native)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/sdkman/candidates/mvnd/0.0.8/mvn
Java version: 14.0.1, vendor: AdoptOpenJDK, runtime: /opt/sdkman/candidates/java/14.0.1.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1031-azure", arch: "amd64", family: "unix"
